import { comprasPadrao } from '@/config/constantes.js';

export const OBRAS_EXEMPLO = [
  {
    id: '1',
    pp: 'PP-9082',
    cliente: 'João Carlos Silva',
    cidade: 'Varginha',
    tipo: 'COM INSTALA\u00c7\u00c3O / COM CONTRAMARCO',
    etapa: 'medicao_inicial',
    responsavel: 'Matheus',
    prazo: '2025-07-15',
    fechamento: '01/07/2025',
    valor: 'R$ 28.500,00',
    pagamento: '50% entrada + 50% instalação',
    obs: 'Cliente com urgência. Apartamento no centro, 3 dormitórios.',
    compras: comprasPadrao(),
    historico: [
      { data: '01/07/2025', hora: '09:12', usuario: 'Ana', acao: 'Obra cadastrada', desc: 'PP-9082 convertida em obra.', tipo: 'criacao' },
      { data: '01/07/2025', hora: '09:15', usuario: 'Sistema', acao: 'Responsável definido', desc: 'Matheus atribuído à Medição Inicial.', tipo: 'sistema' },
    ],
    arquivos: [
      { nome: 'Proposta_PP-9082.xlsx', tipo: 'xls', tamanho: '48 KB', data: '01/07/2025', quem: 'Ana', etapa: 'pedido_inicial', destaque: true, url: null },
      { nome: 'Contrato_PP-9082.json', tipo: 'json', tamanho: '12 KB', data: '01/07/2025', quem: 'Ana', etapa: 'pedido_inicial', destaque: true, url: null },
    ],
    pendencias: [{ id: 'p1', tipo: 'info', texto: 'Aguardando confirmação de horário com o cliente.', criado: '2025-07-01', resolvido: false }],
    criadoEm: '2025-07-01T09:12:00',
    atualizadoEm: '2025-07-01T09:15:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '2',
    pp: 'PP-9075',
    cliente: 'Maria Fernanda Souza',
    cidade: 'Três Pontas',
    tipo: 'COM INSTALA\u00c7\u00c3O / SEM CONTRAMARCO',
    etapa: 'projeto_final',
    responsavel: 'Allana',
    prazo: '2025-07-10',
    fechamento: '20/06/2025',
    valor: 'R$ 15.200,00',
    pagamento: 'À vista',
    obs: 'Prazo apertado.',
    compras: { ...comprasPadrao(), vidro: { status: 'ok', pedido: '', fornecedor: '', obs: '', dataPedido: null }, perfil: { status: 'ok', pedido: '', fornecedor: '', obs: '', dataPedido: null } },
    historico: [
      { data: '20/06/2025', hora: '10:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: '', tipo: 'criacao' },
      { data: '25/06/2025', hora: '14:30', usuario: 'Matheus', acao: 'Medição Final concluída', desc: 'JSON de medição anexado.', tipo: 'etapa' },
      { data: '28/06/2025', hora: '09:00', usuario: 'Allana', acao: 'Projeto Final iniciado', desc: 'Em desenvolvimento.', tipo: 'etapa' },
    ],
    arquivos: [{ nome: 'Medicao_Final_PP-9075.json', tipo: 'json', tamanho: '22 KB', data: '25/06/2025', quem: 'Matheus', etapa: 'medicao_final', destaque: true, url: null }],
    pendencias: [],
    criadoEm: '2025-06-20T10:00:00',
    atualizadoEm: '2025-06-28T09:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '3',
    pp: 'PP-9068',
    cliente: 'Construtora Horizonte LTDA',
    cidade: 'Campanha',
    tipo: 'COM INSTALA\u00c7\u00c3O / COM CONTRAMARCO',
    etapa: 'compras',
    responsavel: 'Andr\u00e9',
    prazo: '2025-07-08',
    fechamento: '10/06/2025',
    valor: 'R$ 87.300,00',
    pagamento: '30/60/90 dias',
    obs: 'Vidro com atraso do fornecedor Cristal Sul.',
    compras: {
      vidro: { status: 'aguardando_entrega', pedido: '25/06', fornecedor: 'Cristal Sul', obs: 'Prev. 10/07', dataPedido: '2025-06-25' },
      acessorios_separacao: { status: 'realizada', pedido: '', fornecedor: '', obs: 'Separação realizada', dataPedido: '2025-06-22' },
      acessorios: { status: 'ok', pedido: '22/06', fornecedor: '', obs: 'Recebido OK', dataPedido: '2025-06-22' },
      perfil_separacao: { status: 'realizada', pedido: '', fornecedor: '', obs: 'Separação realizada', dataPedido: '2025-06-22' },
      perfil: { status: 'ok', pedido: '22/06', fornecedor: '', obs: 'Recebido OK', dataPedido: '2025-06-22' },
    },
    historico: [
      { data: '10/06/2025', hora: '08:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: '', tipo: 'criacao' },
      { data: '01/07/2025', hora: '10:00', usuario: 'Andr\u00e9', acao: 'Compras iniciadas', desc: 'Vidro com atraso - Cristal Sul.', tipo: 'etapa' },
    ],
    arquivos: [
      { nome: 'Medicao_Final_PP-9068.json', tipo: 'json', tamanho: '31 KB', data: '30/06/2025', quem: 'Matheus', etapa: 'medicao_final', destaque: true, url: null },
      { nome: 'Projeto_Final_PP-9068.pdf', tipo: 'pdf', tamanho: '2.1 MB', data: '01/07/2025', quem: 'Allana', etapa: 'projeto_final', destaque: false, url: null },
    ],
    pendencias: [{ id: 'p3', tipo: 'bloqueio', texto: 'Vidro atrasado bloqueando montagem.', criado: '2025-07-01', resolvido: false }],
    criadoEm: '2025-06-10T08:00:00',
    atualizadoEm: '2025-07-01T10:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '4',
    pp: 'PP-9091',
    cliente: 'Roberto Antunes',
    cidade: 'Varginha',
    tipo: 'SEM INSTALA\u00c7\u00c3O / COM ENTREGA',
    etapa: 'montagem',
    responsavel: 'Andr\u00e9',
    prazo: '2025-07-18',
    fechamento: '02/07/2025',
    valor: 'R$ 9.800,00',
    pagamento: '100% entrada',
    obs: 'Entrega semana que vem.',
    compras: { vidro: { status: 'ok' }, acessorios_separacao: { status: 'realizada' }, acessorios: { status: 'ok' }, perfil_separacao: { status: 'realizada' }, perfil: { status: 'ok' } },
    historico: [
      { data: '02/07/2025', hora: '11:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: 'Sem instalação - entrega direta.', tipo: 'criacao' },
      { data: '03/07/2025', hora: '09:00', usuario: 'Andr\u00e9', acao: 'Compras OK - montagem liberada', desc: '', tipo: 'etapa' },
    ],
    arquivos: [],
    pendencias: [],
    criadoEm: '2025-07-02T11:00:00',
    atualizadoEm: '2025-07-03T09:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '5',
    pp: 'PP-9044',
    cliente: 'Supermercado Pão & Sal',
    cidade: 'São Gonçalo do Sapucaí',
    tipo: 'COM INSTALA\u00c7\u00c3O / COM CONTRAMARCO',
    etapa: 'instalacao',
    responsavel: 'Andr\u00e9',
    prazo: '2025-07-07',
    fechamento: '15/05/2025',
    valor: 'R$ 145.000,00',
    pagamento: 'Parcelado conforme contrato',
    obs: 'Equipe 1 designada.',
    compras: { vidro: { status: 'ok' }, acessorios_separacao: { status: 'realizada' }, acessorios: { status: 'ok' }, perfil_separacao: { status: 'realizada' }, perfil: { status: 'ok' } },
    historico: [
      { data: '15/05/2025', hora: '08:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: '', tipo: 'criacao' },
      { data: '01/07/2025', hora: '08:00', usuario: 'Andr\u00e9', acao: 'Montagem concluída - instalação liberada', desc: '', tipo: 'etapa' },
    ],
    arquivos: [
      { nome: 'Contrato_PP-9044.json', tipo: 'json', tamanho: '18 KB', data: '15/05/2025', quem: 'Ana', etapa: 'pedido_inicial', destaque: false, url: null },
      { nome: 'Projeto_Final_PP-9044.pdf', tipo: 'pdf', tamanho: '4.2 MB', data: '20/06/2025', quem: 'Allana', etapa: 'projeto_final', destaque: false, url: null },
    ],
    pendencias: [],
    criadoEm: '2025-05-15T08:00:00',
    atualizadoEm: '2025-07-01T08:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '6',
    pp: 'PP-9101',
    cliente: 'Condomínio Ville Park',
    cidade: 'Varginha',
    tipo: 'COM INSTALA\u00c7\u00c3O / COM CONTRAMARCO',
    etapa: 'pedido_inicial',
    responsavel: 'Matheus',
    prazo: '2025-07-14',
    fechamento: '04/07/2025',
    valor: 'R$ 210.000,00',
    pagamento: '30/70',
    obs: '24 unidades residenciais.',
    compras: comprasPadrao(),
    historico: [{ data: '04/07/2025', hora: '10:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: '24 unidades.', tipo: 'criacao' }],
    arquivos: [{ nome: 'Proposta_PP-9101.xlsx', tipo: 'xls', tamanho: '55 KB', data: '04/07/2025', quem: 'Ana', etapa: 'pedido_inicial', destaque: true, url: null }],
    pendencias: [],
    criadoEm: '2025-07-04T10:00:00',
    atualizadoEm: '2025-07-04T10:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '7',
    pp: 'PP-9055',
    cliente: 'Marcos Vinícius',
    cidade: 'Três Pontas',
    tipo: 'COM INSTALA\u00c7\u00c3O / COM CONTRAMARCO',
    etapa: 'projeto_contramarco',
    responsavel: 'Allana',
    prazo: '2025-07-05',
    fechamento: '15/06/2025',
    valor: 'R$ 18.400,00',
    pagamento: 'Parcelado',
    obs: '',
    compras: comprasPadrao(),
    historico: [
      { data: '15/06/2025', hora: '09:00', usuario: 'Ana', acao: 'Obra cadastrada', desc: '', tipo: 'criacao' },
      { data: '22/06/2025', hora: '11:00', usuario: 'Matheus', acao: 'Medição Inicial concluída', desc: 'JSON de medição anexado.', tipo: 'etapa' },
    ],
    arquivos: [{ nome: 'Medicao_Inicial_PP-9055.json', tipo: 'json', tamanho: '19 KB', data: '22/06/2025', quem: 'Matheus', etapa: 'medicao_inicial', destaque: false, url: null }],
    pendencias: [{ id: 'p7', tipo: 'aviso', texto: 'Projeto contramarco está com prazo vencido.', criado: '2025-07-05', resolvido: false }],
    criadoEm: '2025-06-15T09:00:00',
    atualizadoEm: '2025-06-22T11:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
  {
    id: '8',
    pp: 'PP-9033',
    cliente: 'Carlos Eduardo Pinto',
    cidade: 'Lavras',
    tipo: 'COM INSTALA\u00c7\u00c3O / SEM CONTRAMARCO',
    etapa: 'finalizado',
    responsavel: 'Andr\u00e9',
    prazo: null,
    fechamento: '01/04/2025',
    valor: 'R$ 22.100,00',
    pagamento: 'À vista',
    obs: 'Obra concluída. Cliente satisfeito.',
    compras: { vidro: { status: 'ok' }, acessorios_separacao: { status: 'realizada' }, acessorios: { status: 'ok' }, perfil_separacao: { status: 'realizada' }, perfil: { status: 'ok' } },
    historico: [{ data: '05/05/2025', hora: '17:00', usuario: 'Andr\u00e9', acao: 'Instalação concluída - finalizado', desc: 'VHSys atualizado como atendido.', tipo: 'etapa' }],
    arquivos: [],
    pendencias: [],
    criadoEm: '2025-04-01T10:00:00',
    atualizadoEm: '2025-05-05T17:00:00',
    criadoPor: 'Ana',
    vhsysEsquadria: '',
    vhsysContramarco: '',
    ia_observacoes: [],
  },
];




